server:
  port: 8090

spring:
  #完整路径:spring.sqltoy
#  jackson:
#    # 日期格式化
#    date-format: yyyy-MM-dd HH:mm:ss
#    # 序列化相关
#    serialization:
#      # 格式化输出
#      indent_output: true
#      # 忽略无法转换的对象
#      fail_on_empty_beans: true
#    # 反序列化相关
#    deserialization:
#      # 解析json时，遇到不存在的属性就忽略
#      fail_on_unknown_properties: false
#    # 设置空如何序列化
#    defaultPropertyInclusion: NON_EMPTY
#    parser:
#      # 允许特殊和转义符
#      allow_unquoted_control_chars: true
#      # 允许单引号
#      allow_single_quotes: true
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lover_space?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ljz123hhh
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1
        min-idle: 0
  mail:
    host: smtp.sina.com
    username: gk2018bingo@sina.com
    password: 2989ce3b3c5c9f4a
    default-encoding: utf-8
mybatis:
  mapper-locations: src/main/resources/mapper/*.xml
  type-aliases-package: com.ljz.lover_space.entity
logging:
  config: ./src/main/resources/log4j2-spring.xml
  level:
    com.ljz.lover_space.controller: TRACE

